---
all:
  hosts:
    vps:
      ansible_host: 111.222.3.444
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_port: 22

  vars:
    vps_app_user: user
    vps_timezone: "Europe/Warsaw"
    vps_locale: "en_US.UTF-8"
    vps_github_actions_ssh_required: false